spring:
  data:
    mongodb:
      uri: mongodb+srv://root:QuickStartUp@daario.0489uix.mongodb.net/?retryWrites=true&w=majority&appName=Daario
      database: ShoeStore
  mail:
    host: smtp.gmail.com
    port: 587
    username: truongquanghung345@gmail.com
    password: hunglolcvcl123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  autoconfigure:
    exclude=org:
      springframework:
        boot:
          autoconfigure:
            jdbc:
              DataSourceAutoConfiguration:

server:
  error:
    include-message: always
  servlet:
    session:
      store-type: none